<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit458dfbde137426964b7300a353cb2b73
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rafiur\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rafiur\\' => 
        array (
            0 => __DIR__ . '/../..' . '/packages/Rafiur/TaskManager/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit458dfbde137426964b7300a353cb2b73::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit458dfbde137426964b7300a353cb2b73::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit458dfbde137426964b7300a353cb2b73::$classMap;

        }, null, ClassLoader::class);
    }
}
